In [1]:
import requests
import pandas as pd
from io import StringIO

In [2]:
# to read csv from any url
url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"

# 1. Fetch the content
response = requests.get(url)

# 2. Check if successful (Status 200)
if response.status_code == 200:
    # Use StringIO to treat the string like a file
    csv_data = StringIO(response.text)
    df = pd.read_csv(csv_data)
    # print(df.head())
    display(df)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

In [ ]:
df2 = pd.read_csv('placement.csv', skiprows=[1,4]) # 0th => header row, 1th bhanda tespaxi ko first row
df2

    Unnamed: 0  cgpa     iq  placement
0            1   5.9  106.0          0
1            2   5.3  121.0          0
2            4   5.8  142.0          0
3            5   7.1   48.0          1
4            6   5.7  143.0          0
..         ...   ...    ...        ...
93          95   4.3  200.0          0
94          96   4.4   42.0          0
95          97   6.7  182.0          1
96          98   6.3  103.0          1
97          99   6.2  113.0          1

[98 rows x 4 columns]

In [10]:
df3 = pd.read_csv("placement.csv", usecols=['cgpa', 'iq', 'placement'])

In [11]:
df3

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

In [12]:
df4 = pd.read_csv("placement.csv", skiprows= lambda x: x%5 == 0)

In [13]:
df4

     0  6.8  123.0  1
0    1  5.9  106.0  0
1    2  5.3  121.0  0
2    3  7.4  132.0  1
3    5  7.1   48.0  1
4    6  5.7  143.0  0
..  ..  ...    ... ..
74  93  6.8  112.0  1
75  95  4.3  200.0  0
76  96  4.4   42.0  0
77  97  6.7  182.0  1
78  98  6.3  103.0  1

[79 rows x 4 columns]

In [15]:
df5 = pd.read_csv('placement.csv', nrows=4)
df5

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1

In [17]:
df6 = pd.read_csv('placement.csv', encoding='latin-1')

In [26]:
pd.to_datetime("2025-04-02 5:0:1")

Timestamp('2025-04-02 05:00:01')