<a href="https://colab.research.google.com/github/SakshiKhatiwada/Python/blob/main/Deep-Learning/Backpropagation_manual_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import numpy as np
import pandas as pd

In [59]:
df = pd.DataFrame([[8,8,4],[7,9,5], [6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [60]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [61]:
def initialization_parameters(layer_dim):
  parameters = {}
  np.random.seed(3)
  L = len(layer_dim)
  for l in range(1,L):
    parameters['W'+str(l)] = np.ones((layer_dim[l-1],layer_dim[l]))* 0.1
    parameters['b'+str(l)] = np.zeros((layer_dim[l], 1))
  return parameters

In [62]:
initialization_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [63]:
def linear_forward(A_prev, W,b):
  Z = np.dot(W.T, A_prev) + b
  return Z

In [80]:
# Forward Propagation

def L_layer_forward(X, parameters):
  A = X
  L = len(parameters) // 2 # => no. of layers in NN

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]

    # print("A" + str(l-1)+ ": ", A_prev)
    # print("W" + str(l) + ": ", Wl)
    # print("b" + str(l) + ": ", bl)
    # print("--" * 20)

    A = linear_forward(A_prev, Wl, bl)
    # print("A" + str(l) + ": ", A)
    # print("**" * 20)

  return A,A_prev

In [65]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # shape (no. of features, no. of training example)
y = df[['lpa']].values[0][0]

In [66]:
df[['lpa']]

   lpa
0    4
1    5
2    6
3    7

In [67]:
# Parameter Initialization

parameters = initialization_parameters([2,2,1])
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [68]:
y_hat, A1 = L_layer_forward(X, parameters)

A0:  [[8]
 [8]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6]
 [1.6]]
****************************************
A1:  [[1.6]
 [1.6]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32]]
****************************************

In [69]:
y_hat = y_hat[0,0]

In [70]:
A1

array([[1.6],
       [1.6]])

In [71]:
# loss
(y - 0.32) ** 2

np.float64(13.5424)

In [72]:
def update_parameters(parameters, y, y_hat, A1, X):
  temp = 0.001 * 2 * (y-y_hat)
  parameters['W2'][0][0] += ( temp * A1[0][0])
  parameters['W2'][1][0] += ( temp  * A1[1][0])
  parameters['b2'][0][0] += ( temp )

  parameters['W1'][0][0] += (temp * parameters['W2'][0][0] * X[0][0])
  parameters['W1'][0][1] += (temp * parameters['W2'][0][0] * X[1][0])
  parameters['b1'][0][0] += (temp * parameters['W2'][0][0])

  parameters['W1'][1][0] += (temp * parameters['W2'][1][0] * X[0][0])
  parameters['W1'][1][1] += (temp * parameters['W2'][1][0] * X[1][0])
  parameters['b1'][1][0] += (temp * parameters['W2'][1][0])

In [73]:
update_parameters(parameters, y, y_hat, A1, X)

In [74]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [75]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # shape (no. of features, no. of training example)
y = df[['lpa']].values[1][0]

y_hat, A1 = L_layer_forward(X, parameters)

A0:  [[7]
 [9]]
W1:  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1:  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1:  [[1.70612461]
 [1.70612461]]
****************************************
A1:  [[1.70612461]
 [1.70612461]]
W2:  [[0.111776]
 [0.111776]]
b2:  [[0.00736]]
----------------------------------------
A2:  [[0.38876757]]
****************************************

In [76]:
y_hat = y_hat[0,0]
update_parameters(parameters, y, y_hat, A1, X)

In [77]:
parameters

{'W1': array([[0.11481311, 0.11716504],
        [0.11481311, 0.11716504]]),
 'b1': array([[0.00199863],
        [0.00199863]]),
 'W2': array([[0.12751067],
        [0.12751067]]),
 'b2': array([[0.01658246]])}

In [81]:
# and continueeeeeeee...


# Implementing all in one: Epochs Implementation

parameters = initialization_parameters([2,2,1])
epochs = 3

for i in range(epochs):
  loss = []

  for j in range(df.shape[0]):
    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1)
    # shape (no. of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # parameter initialization

    y_hat, A1 = L_layer_forward(X, parameters)
    y_hat = y_hat[0,0]

    update_parameters(parameters, y, y_hat, A1, X)

    loss.append((y-y_hat)**2)

  print("Epoch-", i+1, 'loss: ', np.array(loss).mean())

parameters

Epoch- 1 loss:  26.28249792398698
Epoch- 2 loss:  19.438253848220803
Epoch- 3 loss:  10.139874435827522

{'W1': array([[0.23186978, 0.31964643],
        [0.23955518, 0.33335352]]),
 'b1': array([[0.02148378],
        [0.02278422]]),
 'W2': array([[0.34626065],
        [0.39077259]]),
 'b2': array([[0.09965587]])}