<a href="https://colab.research.google.com/github/SakshiKhatiwada/Python/blob/main/Deep-Learning/keras_hyperparameter_tuning_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("diabetes.csv")

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [5]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [7]:
X = scaler.fit_transform(X)

In [8]:
X.shape

(768, 8)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=52 )

In [10]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [11]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [12]:
model.fit(X_train, y_train, batch_size= 32, epochs = 100, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5349 - loss: 0.6957 - val_accuracy: 0.6429 - val_loss: 0.6364
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6916 - loss: 0.6480 - val_accuracy: 0.7338 - val_loss: 0.5919
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7447 - loss: 0.5699 - val_accuracy: 0.7403 - val_loss: 0.5596
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7635 - loss: 0.5554 - val_accuracy: 0.7597 - val_loss: 0.5376
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7456 - loss: 0.5357 - val_accuracy: 0.7532 - val_loss: 0.5219
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7805 - loss: 0.5123 - val_accuracy: 0.7468 - val_loss: 0.5102
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7718 - loss: 0.5093 - val_accuracy: 0.7532 - val_loss: 0.5016
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7849 - loss: 0.4909 - val_accuracy: 0.7662 - val_loss: 0.4972
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7676 - loss: 0.4992 - val_accuracy: 0.7662 - val_loss: 0.4920
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7788 - loss: 0.4681 - val_accuracy: 0.7597 - val_loss: 0.4927
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7842 - loss: 0.4580 - val_accuracy: 0.7662 - val_loss: 0.4898
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7824 - loss: 0.4708 - val_accuracy: 0.7727 - val_loss: 0.4872
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7768 - loss: 0.4779 - val_accuracy: 0.7727 - val_loss: 0.4887
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7542 - loss: 0.4891 - val_accuracy: 0.7662 - val_loss: 0.4871
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8061 - loss: 0.4246 - val_accuracy: 0.7662 - val_loss: 0.4865
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7741 - loss: 0.4548 - val_accuracy: 0.7662 - val_loss: 0.4843
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7889 - loss: 0.4474 - val_accuracy: 0.7727 - val_loss: 0.4857
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7849 - loss: 0.4460 - val_accuracy: 0.7727 - val_loss: 0.4854
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7949 - loss: 0.4283 - val_accuracy: 0.7792 - val_loss: 0.4839
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7599 - loss: 0.4793 - val_accuracy: 0.7727 - val_loss: 0.4853
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7661 - loss: 0.4589 - val_accuracy: 0.7662 - val_loss: 0.4862
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8031 - loss: 0.4342 - val_accuracy: 0.7662 - val_loss: 0.4860
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7743 - loss: 0.4545 - val_accuracy: 0.7597 - val_loss: 0.4869
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7694 - loss: 0.4613 - val_accuracy: 0.7532 - val_loss: 0.4868
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7922 - loss: 0.4290 - val_accuracy: 0.7532 - val_loss: 0.4867
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8093 - loss: 0.4108 - val_accuracy: 0.7532 - val_loss: 0.4855
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7856 - loss: 0.4517 - val_accuracy: 0.7597 - val_loss: 0.4842
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8063 - loss: 0.4168 - val_accuracy: 0.7532 - val_loss: 0.4867
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7839 - loss: 0.4435 - val_accuracy: 0.7597 - val_loss: 0.4850
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7978 - loss: 0.4343 - val_accuracy: 0.7532 - val_loss: 0.4884
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7901 - loss: 0.4386 - val_accuracy: 0.7532 - val_loss: 0.4882
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8073 - loss: 0.4286 - val_accuracy: 0.7532 - val_loss: 0.4887
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7979 - loss: 0.4247 - val_accuracy: 0.7532 - val_loss: 0.4896
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7822 - loss: 0.4363 - val_accuracy: 0.7597 - val_loss: 0.4894
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7952 - loss: 0.4279 - val_accuracy: 0.7597 - val_loss: 0.4865
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7930 - loss: 0.4297 - val_accuracy: 0.7532 - val_loss: 0.4869
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8049 - loss: 0.4244 - val_accuracy: 0.7597 - val_loss: 0.4874
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7917 - loss: 0.4274 - val_accuracy: 0.7597 - val_loss: 0.4887
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7897 - loss: 0.4426 - val_accuracy: 0.7597 - val_loss: 0.4881
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7825 - loss: 0.4322 - val_accuracy: 0.7597 - val_loss: 0.4896
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8056 - loss: 0.4175 - val_accuracy: 0.7532 - val_loss: 0.4892
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8040 - loss: 0.4129 - val_accuracy: 0.7532 - val_loss: 0.4892
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7808 - loss: 0.4300 - val_accuracy: 0.7597 - val_loss: 0.4874
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8037 - loss: 0.4162 - val_accuracy: 0.7597 - val_loss: 0.4857
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7667 - loss: 0.4645 - val_accuracy: 0.7532 - val_loss: 0.4853
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8005 - loss: 0.4347 - val_accuracy: 0.7532 - val_loss: 0.4873
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8167 - loss: 0.3948 - val_accuracy: 0.7532 - val_loss: 0.4864
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7952 - loss: 0.4253 - val_accuracy: 0.7532 - val_loss: 0.4867
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8076 - loss: 0.4215 - val_accuracy: 0.7532 - val_loss: 0.4883
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7924 - loss: 0.4074 - val_accuracy: 0.7532 - val_loss: 0.4864
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7875 - loss: 0.4219 - val_accuracy: 0.7532 - val_loss: 0.4871
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7791 - loss: 0.4429 - val_accuracy: 0.7532 - val_loss: 0.4881
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8052 - loss: 0.4221 - val_accuracy: 0.7597 - val_loss: 0.4874
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8023 - loss: 0.4039 - val_accuracy: 0.7532 - val_loss: 0.4879
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7914 - loss: 0.4168 - val_accuracy: 0.7532 - val_loss: 0.4884
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8161 - loss: 0.3905 - val_accuracy: 0.7532 - val_loss: 0.4876
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8019 - loss: 0.4129 - val_accuracy: 0.7532 - val_loss: 0.4896
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3915 - val_accuracy: 0.7532 - val_loss: 0.4898
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7982 - loss: 0.4189 - val_accuracy: 0.7532 - val_loss: 0.4893
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8147 - loss: 0.4090 - val_accuracy: 0.7597 - val_loss: 0.4876
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8185 - loss: 0.4018 - val_accuracy: 0.7597 - val_loss: 0.4900
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8362 - loss: 0.3711 - val_accuracy: 0.7532 - val_loss: 0.4932
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7885 - loss: 0.4342 - val_accuracy: 0.7532 - val_loss: 0.4916
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7957 - loss: 0.4144 - val_accuracy: 0.7468 - val_loss: 0.4911
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7920 - loss: 0.4255 - val_accuracy: 0.7468 - val_loss: 0.4902
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8130 - loss: 0.4313 - val_accuracy: 0.7532 - val_loss: 0.4902
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8049 - loss: 0.4166 - val_accuracy: 0.7532 - val_loss: 0.4909
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8063 - loss: 0.3902 - val_accuracy: 0.7532 - val_loss: 0.4910
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8028 - loss: 0.4286 - val_accuracy: 0.7597 - val_loss: 0.4898
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8052 - loss: 0.4089 - val_accuracy: 0.7662 - val_loss: 0.4940
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8074 - loss: 0.4085 - val_accuracy: 0.7597 - val_loss: 0.4926
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8222 - loss: 0.3971 - val_accuracy: 0.7532 - val_loss: 0.4914
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8365 - loss: 0.3664 - val_accuracy: 0.7532 - val_loss: 0.4892
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8250 - loss: 0.4100 - val_accuracy: 0.7532 - val_loss: 0.4896
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8058 - loss: 0.4286 - val_accuracy: 0.7532 - val_loss: 0.4907
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8103 - loss: 0.4084 - val_accuracy: 0.7468 - val_loss: 0.4922
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8043 - loss: 0.4169 - val_accuracy: 0.7532 - val_loss: 0.4898
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8150 - loss: 0.4185 - val_accuracy: 0.7532 - val_loss: 0.4936
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8295 - loss: 0.3839 - val_accuracy: 0.7597 - val_loss: 0.4940
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8040 - loss: 0.4136 - val_accuracy: 0.7597 - val_loss: 0.4943
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8262 - loss: 0.3968 - val_accuracy: 0.7468 - val_loss: 0.4955
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8201 - loss: 0.4155 - val_accuracy: 0.7468 - val_loss: 0.4943
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8182 - loss: 0.3999 - val_accuracy: 0.7597 - val_loss: 0.4897
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8181 - loss: 0.4021 - val_accuracy: 0.7597 - val_loss: 0.4908
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8327 - loss: 0.3891 - val_accuracy: 0.7468 - val_loss: 0.4924
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8191 - loss: 0.4018 - val_accuracy: 0.7468 - val_loss: 0.4908
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7963 - loss: 0.4186 - val_accuracy: 0.7468 - val_loss: 0.4893
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8286 - loss: 0.3925 - val_accuracy: 0.7597 - val_loss: 0.4881
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8240 - loss: 0.3964 - val_accuracy: 0.7468 - val_loss: 0.4920
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8144 - loss: 0.4247 - val_accuracy: 0.7468 - val_loss: 0.4924
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8356 - loss: 0.3980 - val_accuracy: 0.7468 - val_loss: 0.4903
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7944 - loss: 0.4220 - val_accuracy: 0.7468 - val_loss: 0.4919
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8276 - loss: 0.3952 - val_accuracy: 0.7468 - val_loss: 0.4918
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8085 - loss: 0.4176 - val_accuracy: 0.7532 - val_loss: 0.4884
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8010 - loss: 0.4082 - val_accuracy: 0.7597 - val_loss: 0.4901
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8182 - loss: 0.4037 - val_accuracy: 0.7532 - val_loss: 0.4909
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8213 - loss: 0.4072 - val_accuracy: 0.7468 - val_loss: 0.4929
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8193 - loss: 0.3960 - val_accuracy: 0.7597 - val_loss: 0.4905
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8161 - loss: 0.4047 - val_accuracy: 0.7532 - val_loss: 0.4923
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4268 - val_accuracy: 0.7468 - val_loss: 0.4928

In [13]:
!pip install -U keras-tuner
import kerastuner as kt

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (25.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.15.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.17.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2025.10.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras->keras-tuner) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 8.7 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

/tmp/ipython-input-3209566528.py:2: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [14]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta'])
  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [15]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5
    )

In [16]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test, y_test))

Trial 4 Complete [00h 00m 07s]
val_accuracy: 0.4675324559211731

Best val_accuracy So Far: 0.7727272510528564
Total elapsed time: 00h 00m 23s

In [17]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [18]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7476 - loss: 0.5622 - val_accuracy: 0.7792 - val_loss: 0.5264
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7605 - loss: 0.5346 - val_accuracy: 0.7792 - val_loss: 0.5118
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7796 - loss: 0.4971 - val_accuracy: 0.7727 - val_loss: 0.5017
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7960 - loss: 0.4849 - val_accuracy: 0.7662 - val_loss: 0.4958
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7738 - loss: 0.4944 - val_accuracy: 0.7662 - val_loss: 0.4903
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7870 - loss: 0.4667 - val_accuracy: 0.7792 - val_loss: 0.4875
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7902 - loss: 0.4632 - val_accuracy: 0.7662 - val_loss: 0.4868
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7659 - loss: 0.4940 - val_accuracy: 0.7727 - val_loss: 0.4855
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7768 - loss: 0.4791 - val_accuracy: 0.7727 - val_loss: 0.4859
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7829 - loss: 0.4715 - val_accuracy: 0.7792 - val_loss: 0.4865
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7528 - loss: 0.4831 - val_accuracy: 0.7662 - val_loss: 0.4886
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7871 - loss: 0.4641 - val_accuracy: 0.7597 - val_loss: 0.4889
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7943 - loss: 0.4527 - val_accuracy: 0.7597 - val_loss: 0.4902
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7813 - loss: 0.4630 - val_accuracy: 0.7662 - val_loss: 0.4899
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7998 - loss: 0.4501 - val_accuracy: 0.7727 - val_loss: 0.4884
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8012 - loss: 0.4558 - val_accuracy: 0.7792 - val_loss: 0.4875
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7787 - loss: 0.4706 - val_accuracy: 0.7792 - val_loss: 0.4877
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7836 - loss: 0.4694 - val_accuracy: 0.7792 - val_loss: 0.4903
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7998 - loss: 0.4378 - val_accuracy: 0.7792 - val_loss: 0.4917
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8054 - loss: 0.4402 - val_accuracy: 0.7792 - val_loss: 0.4948
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7878 - loss: 0.4566 - val_accuracy: 0.7792 - val_loss: 0.4947
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7760 - loss: 0.4629 - val_accuracy: 0.7792 - val_loss: 0.4939
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7996 - loss: 0.4428 - val_accuracy: 0.7792 - val_loss: 0.4957
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7961 - loss: 0.4408 - val_accuracy: 0.7857 - val_loss: 0.4958
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.7993 - loss: 0.4339 - val_accuracy: 0.7857 - val_loss: 0.4947
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.8010 - loss: 0.4197 - val_accuracy: 0.7857 - val_loss: 0.4973
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7899 - loss: 0.4513 - val_accuracy: 0.7857 - val_loss: 0.4964
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7893 - loss: 0.4372 - val_accuracy: 0.7857 - val_loss: 0.4983
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7999 - loss: 0.4187 - val_accuracy: 0.7727 - val_loss: 0.4981
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7804 - loss: 0.4355 - val_accuracy: 0.7727 - val_loss: 0.4982
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7777 - loss: 0.4306 - val_accuracy: 0.7792 - val_loss: 0.4974
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8047 - loss: 0.4304 - val_accuracy: 0.7857 - val_loss: 0.4963
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7845 - loss: 0.4299 - val_accuracy: 0.7792 - val_loss: 0.4960
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7923 - loss: 0.4189 - val_accuracy: 0.7727 - val_loss: 0.4969
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8119 - loss: 0.4303 - val_accuracy: 0.7727 - val_loss: 0.4970
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8010 - loss: 0.4274 - val_accuracy: 0.7662 - val_loss: 0.4979
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7837 - loss: 0.4442 - val_accuracy: 0.7662 - val_loss: 0.4981
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7788 - loss: 0.4557 - val_accuracy: 0.7662 - val_loss: 0.4986
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8069 - loss: 0.4233 - val_accuracy: 0.7727 - val_loss: 0.4983
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8217 - loss: 0.4078 - val_accuracy: 0.7727 - val_loss: 0.4975
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7974 - loss: 0.4208 - val_accuracy: 0.7727 - val_loss: 0.4978
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8132 - loss: 0.4015 - val_accuracy: 0.7727 - val_loss: 0.4972
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7975 - loss: 0.4119 - val_accuracy: 0.7727 - val_loss: 0.4988
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7849 - loss: 0.4362 - val_accuracy: 0.7662 - val_loss: 0.5014
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.7989 - loss: 0.4263 - val_accuracy: 0.7662 - val_loss: 0.5005
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7957 - loss: 0.4262 - val_accuracy: 0.7662 - val_loss: 0.4992
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8052 - loss: 0.4075 - val_accuracy: 0.7662 - val_loss: 0.4977
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8001 - loss: 0.4276 - val_accuracy: 0.7662 - val_loss: 0.4993
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8036 - loss: 0.4321 - val_accuracy: 0.7662 - val_loss: 0.5005
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7845 - loss: 0.4323 - val_accuracy: 0.7662 - val_loss: 0.4999
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8186 - loss: 0.4141 - val_accuracy: 0.7662 - val_loss: 0.4999
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7929 - loss: 0.4377 - val_accuracy: 0.7662 - val_loss: 0.5021
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7780 - loss: 0.4453 - val_accuracy: 0.7662 - val_loss: 0.5032
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7942 - loss: 0.4104 - val_accuracy: 0.7662 - val_loss: 0.5013
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7869 - loss: 0.4444 - val_accuracy: 0.7662 - val_loss: 0.4976
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8073 - loss: 0.4062 - val_accuracy: 0.7662 - val_loss: 0.4999
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7996 - loss: 0.3956 - val_accuracy: 0.7662 - val_loss: 0.5021
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8084 - loss: 0.4104 - val_accuracy: 0.7662 - val_loss: 0.5030
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7984 - loss: 0.4080 - val_accuracy: 0.7662 - val_loss: 0.5032
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7848 - loss: 0.4332 - val_accuracy: 0.7662 - val_loss: 0.5017
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8112 - loss: 0.4086 - val_accuracy: 0.7662 - val_loss: 0.5014
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7855 - loss: 0.4603 - val_accuracy: 0.7662 - val_loss: 0.5017
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7938 - loss: 0.4242 - val_accuracy: 0.7662 - val_loss: 0.5014
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8099 - loss: 0.4315 - val_accuracy: 0.7662 - val_loss: 0.5009
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7990 - loss: 0.4269 - val_accuracy: 0.7597 - val_loss: 0.4984
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8050 - loss: 0.4340 - val_accuracy: 0.7597 - val_loss: 0.4994
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7972 - loss: 0.4248 - val_accuracy: 0.7597 - val_loss: 0.5028
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7737 - loss: 0.4555 - val_accuracy: 0.7597 - val_loss: 0.5017
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7933 - loss: 0.4088 - val_accuracy: 0.7597 - val_loss: 0.5019
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7982 - loss: 0.4334 - val_accuracy: 0.7727 - val_loss: 0.5014
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7875 - loss: 0.4373 - val_accuracy: 0.7597 - val_loss: 0.5025
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7921 - loss: 0.4186 - val_accuracy: 0.7597 - val_loss: 0.5026
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8099 - loss: 0.4214 - val_accuracy: 0.7597 - val_loss: 0.5023
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8059 - loss: 0.4011 - val_accuracy: 0.7597 - val_loss: 0.5025
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8001 - loss: 0.4095 - val_accuracy: 0.7597 - val_loss: 0.5019
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7886 - loss: 0.4267 - val_accuracy: 0.7597 - val_loss: 0.5007
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7988 - loss: 0.4030 - val_accuracy: 0.7597 - val_loss: 0.5004
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8040 - loss: 0.4098 - val_accuracy: 0.7597 - val_loss: 0.5029
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7926 - loss: 0.4323 - val_accuracy: 0.7597 - val_loss: 0.5000
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8147 - loss: 0.3912 - val_accuracy: 0.7597 - val_loss: 0.5016
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8131 - loss: 0.4031 - val_accuracy: 0.7597 - val_loss: 0.5005
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8105 - loss: 0.4087 - val_accuracy: 0.7597 - val_loss: 0.5006
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7901 - loss: 0.4257 - val_accuracy: 0.7597 - val_loss: 0.5027
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7975 - loss: 0.4045 - val_accuracy: 0.7597 - val_loss: 0.5037
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8037 - loss: 0.3980 - val_accuracy: 0.7597 - val_loss: 0.5033
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7968 - loss: 0.4203 - val_accuracy: 0.7597 - val_loss: 0.5042
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8310 - loss: 0.4029 - val_accuracy: 0.7597 - val_loss: 0.5032
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8081 - loss: 0.4104 - val_accuracy: 0.7597 - val_loss: 0.5039
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8119 - loss: 0.3960 - val_accuracy: 0.7597 - val_loss: 0.5029
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7833 - loss: 0.4311 - val_accuracy: 0.7597 - val_loss: 0.5045
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8161 - loss: 0.3909 - val_accuracy: 0.7597 - val_loss: 0.5038
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.3904 - val_accuracy: 0.7597 - val_loss: 0.5040
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8010 - loss: 0.4257 - val_accuracy: 0.7597 - val_loss: 0.5023
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8037 - loss: 0.4076 - val_accuracy: 0.7597 - val_loss: 0.5018

In [21]:
# to find the optimal no. of nodes

def build_model2(hp):

  model = Sequential()
  units = hp.Int('units', min_value=8, max_value=128, step=8) # lower and upper limit, step size
  model.add(Dense(units = units, activation='relu', input_dim = 8))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [22]:
tuner = kt.RandomSearch(build_model2, objective='val_accuracy', max_trials=5,
                        directory='mydir')

In [23]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 12s

In [24]:
tuner.get_best_hyperparameters()[0].values

{'units': 56}

In [25]:
model = tuner.get_best_models(num_models=1)[0]

In [26]:
model.fit(X_train, y_train, batch_size=32, epochs = 100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7544 - loss: 0.4940 - val_accuracy: 0.7987 - val_loss: 0.4860
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7451 - loss: 0.5019 - val_accuracy: 0.8052 - val_loss: 0.4834
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7661 - loss: 0.4581 - val_accuracy: 0.7987 - val_loss: 0.4829
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7577 - loss: 0.4860 - val_accuracy: 0.7987 - val_loss: 0.4823
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7728 - loss: 0.4675 - val_accuracy: 0.7922 - val_loss: 0.4815
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7745 - loss: 0.4705 - val_accuracy: 0.7922 - val_loss: 0.4820
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7745 - loss: 0.4635 - val_accuracy: 0.7922 - val_loss: 0.4813
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8005 - loss: 0.4401 - val_accuracy: 0.7792 - val_loss: 0.4807
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7802 - loss: 0.4498 - val_accuracy: 0.7727 - val_loss: 0.4814
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7875 - loss: 0.4451 - val_accuracy: 0.7727 - val_loss: 0.4826
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7739 - loss: 0.4514 - val_accuracy: 0.7792 - val_loss: 0.4835
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7683 - loss: 0.4379 - val_accuracy: 0.7727 - val_loss: 0.4830
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7821 - loss: 0.4421 - val_accuracy: 0.7792 - val_loss: 0.4827
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7891 - loss: 0.4363 - val_accuracy: 0.7792 - val_loss: 0.4822
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7754 - loss: 0.4444 - val_accuracy: 0.7792 - val_loss: 0.4820
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7918 - loss: 0.4399 - val_accuracy: 0.7792 - val_loss: 0.4824
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7941 - loss: 0.4111 - val_accuracy: 0.7792 - val_loss: 0.4841
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4367 - val_accuracy: 0.7792 - val_loss: 0.4847
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7717 - loss: 0.4381 - val_accuracy: 0.7857 - val_loss: 0.4837
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7813 - loss: 0.4549 - val_accuracy: 0.7727 - val_loss: 0.4839
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8015 - loss: 0.4164 - val_accuracy: 0.7792 - val_loss: 0.4846
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7906 - loss: 0.4143 - val_accuracy: 0.7792 - val_loss: 0.4855
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8064 - loss: 0.4126 - val_accuracy: 0.7792 - val_loss: 0.4852
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7958 - loss: 0.4173 - val_accuracy: 0.7792 - val_loss: 0.4860
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7930 - loss: 0.4175 - val_accuracy: 0.7792 - val_loss: 0.4850
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7958 - loss: 0.4205 - val_accuracy: 0.7792 - val_loss: 0.4853
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4132 - val_accuracy: 0.7792 - val_loss: 0.4864
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8071 - loss: 0.4049 - val_accuracy: 0.7727 - val_loss: 0.4861
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8165 - loss: 0.4046 - val_accuracy: 0.7727 - val_loss: 0.4857
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8057 - loss: 0.4197 - val_accuracy: 0.7727 - val_loss: 0.4855
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7996 - loss: 0.4300 - val_accuracy: 0.7727 - val_loss: 0.4864
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8009 - loss: 0.4245 - val_accuracy: 0.7727 - val_loss: 0.4858
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8077 - loss: 0.4065 - val_accuracy: 0.7727 - val_loss: 0.4846
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8113 - loss: 0.4109 - val_accuracy: 0.7727 - val_loss: 0.4864
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8053 - loss: 0.4017 - val_accuracy: 0.7727 - val_loss: 0.4873
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8084 - loss: 0.4108 - val_accuracy: 0.7727 - val_loss: 0.4864
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8128 - loss: 0.4094 - val_accuracy: 0.7727 - val_loss: 0.4873
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8115 - loss: 0.4157 - val_accuracy: 0.7727 - val_loss: 0.4877
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7782 - loss: 0.4558 - val_accuracy: 0.7727 - val_loss: 0.4885
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8079 - loss: 0.4133 - val_accuracy: 0.7727 - val_loss: 0.4894
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8329 - loss: 0.3824 - val_accuracy: 0.7727 - val_loss: 0.4882
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8002 - loss: 0.4275 - val_accuracy: 0.7727 - val_loss: 0.4897
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8141 - loss: 0.4026 - val_accuracy: 0.7727 - val_loss: 0.4900
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8215 - loss: 0.4008 - val_accuracy: 0.7662 - val_loss: 0.4897
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8061 - loss: 0.4279 - val_accuracy: 0.7727 - val_loss: 0.4899
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8072 - loss: 0.4090 - val_accuracy: 0.7727 - val_loss: 0.4886
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7813 - loss: 0.4280 - val_accuracy: 0.7662 - val_loss: 0.4902
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8145 - loss: 0.3857 - val_accuracy: 0.7597 - val_loss: 0.4919
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8092 - loss: 0.3958 - val_accuracy: 0.7597 - val_loss: 0.4915
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8149 - loss: 0.4103 - val_accuracy: 0.7662 - val_loss: 0.4908
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7996 - loss: 0.4245 - val_accuracy: 0.7727 - val_loss: 0.4899
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8331 - loss: 0.3908 - val_accuracy: 0.7727 - val_loss: 0.4906
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3657 - val_accuracy: 0.7727 - val_loss: 0.4908
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8082 - loss: 0.3945 - val_accuracy: 0.7727 - val_loss: 0.4913
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7961 - loss: 0.4024 - val_accuracy: 0.7662 - val_loss: 0.4908
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8102 - loss: 0.4027 - val_accuracy: 0.7597 - val_loss: 0.4922
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8044 - loss: 0.4058 - val_accuracy: 0.7662 - val_loss: 0.4942
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8266 - loss: 0.4001 - val_accuracy: 0.7662 - val_loss: 0.4918
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8066 - loss: 0.4061 - val_accuracy: 0.7727 - val_loss: 0.4930
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7984 - loss: 0.4242 - val_accuracy: 0.7597 - val_loss: 0.4943
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8149 - loss: 0.4018 - val_accuracy: 0.7597 - val_loss: 0.4955
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8315 - loss: 0.3783 - val_accuracy: 0.7597 - val_loss: 0.4961
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8430 - loss: 0.3769 - val_accuracy: 0.7597 - val_loss: 0.4993
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8139 - loss: 0.4109 - val_accuracy: 0.7597 - val_loss: 0.4950
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4154 - val_accuracy: 0.7597 - val_loss: 0.4953
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8132 - loss: 0.4022 - val_accuracy: 0.7597 - val_loss: 0.4970
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8278 - loss: 0.3878 - val_accuracy: 0.7597 - val_loss: 0.4955
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8186 - loss: 0.3871 - val_accuracy: 0.7597 - val_loss: 0.4975
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8263 - loss: 0.3786 - val_accuracy: 0.7597 - val_loss: 0.4971
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8166 - loss: 0.4131 - val_accuracy: 0.7597 - val_loss: 0.4976
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8188 - loss: 0.3921 - val_accuracy: 0.7662 - val_loss: 0.4962
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8196 - loss: 0.3883 - val_accuracy: 0.7597 - val_loss: 0.4972
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8199 - loss: 0.4121 - val_accuracy: 0.7597 - val_loss: 0.4976
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8385 - loss: 0.3953 - val_accuracy: 0.7532 - val_loss: 0.4978
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8178 - loss: 0.4131 - val_accuracy: 0.7532 - val_loss: 0.4986
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8337 - loss: 0.3876 - val_accuracy: 0.7532 - val_loss: 0.5001
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8283 - loss: 0.3986 - val_accuracy: 0.7532 - val_loss: 0.5013
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8179 - loss: 0.3987 - val_accuracy: 0.7532 - val_loss: 0.5035
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8051 - loss: 0.4174 - val_accuracy: 0.7532 - val_loss: 0.5046
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8243 - loss: 0.3962 - val_accuracy: 0.7532 - val_loss: 0.5053
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3899 - val_accuracy: 0.7532 - val_loss: 0.5051
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8278 - loss: 0.4129 - val_accuracy: 0.7532 - val_loss: 0.5043
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8319 - loss: 0.3975 - val_accuracy: 0.7532 - val_loss: 0.5012
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8142 - loss: 0.4033 - val_accuracy: 0.7468 - val_loss: 0.5036
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8412 - loss: 0.3826 - val_accuracy: 0.7532 - val_loss: 0.5040
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8226 - loss: 0.4073 - val_accuracy: 0.7532 - val_loss: 0.5033
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8391 - loss: 0.3864 - val_accuracy: 0.7532 - val_loss: 0.5050
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8301 - loss: 0.3808 - val_accuracy: 0.7532 - val_loss: 0.5065
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8147 - loss: 0.4075 - val_accuracy: 0.7468 - val_loss: 0.5067
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8324 - loss: 0.3882 - val_accuracy: 0.7468 - val_loss: 0.5080
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8177 - loss: 0.4075 - val_accuracy: 0.7468 - val_loss: 0.5091
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3844 - val_accuracy: 0.7532 - val_loss: 0.5101
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8240 - loss: 0.3970 - val_accuracy: 0.7532 - val_loss: 0.5098
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8297 - loss: 0.4010 - val_accuracy: 0.7468 - val_loss: 0.5115

In [27]:
# To Select the no. of layers
def build_model3(hp):
  model = Sequential()
  model.add(Dense(72, activation='relu', input_dim=8))

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    model.add(Dense(72, activation='relu'))

  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [28]:
tuner = kt.RandomSearch(build_model3,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name='hero-me')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [29]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.7792207598686218

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 00m 10s

In [31]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 8 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [32]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7488 - loss: 0.5136 - val_accuracy: 0.7857 - val_loss: 0.4773
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7744 - loss: 0.4524 - val_accuracy: 0.7922 - val_loss: 0.4805
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7780 - loss: 0.4429 - val_accuracy: 0.7727 - val_loss: 0.4834
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4737 - val_accuracy: 0.7857 - val_loss: 0.4836
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7859 - loss: 0.4354 - val_accuracy: 0.7857 - val_loss: 0.4853
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7635 - loss: 0.4627 - val_accuracy: 0.7792 - val_loss: 0.4924
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7893 - loss: 0.4348 - val_accuracy: 0.7792 - val_loss: 0.4926
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8097 - loss: 0.4062 - val_accuracy: 0.7727 - val_loss: 0.4892
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8122 - loss: 0.4111 - val_accuracy: 0.7792 - val_loss: 0.4971
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7826 - loss: 0.4249 - val_accuracy: 0.7727 - val_loss: 0.4886
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7912 - loss: 0.4350 - val_accuracy: 0.7727 - val_loss: 0.4984
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8089 - loss: 0.4036 - val_accuracy: 0.7727 - val_loss: 0.4942
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7868 - loss: 0.4282 - val_accuracy: 0.7727 - val_loss: 0.5016
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3926 - val_accuracy: 0.7662 - val_loss: 0.4953
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8354 - loss: 0.3751 - val_accuracy: 0.7727 - val_loss: 0.4985
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8217 - loss: 0.3787 - val_accuracy: 0.7662 - val_loss: 0.5025
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8349 - loss: 0.3808 - val_accuracy: 0.7792 - val_loss: 0.4965
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8103 - loss: 0.4109 - val_accuracy: 0.7597 - val_loss: 0.5010
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8073 - loss: 0.4332 - val_accuracy: 0.7727 - val_loss: 0.5021
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8136 - loss: 0.3910 - val_accuracy: 0.7597 - val_loss: 0.5124
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8374 - loss: 0.3938 - val_accuracy: 0.7597 - val_loss: 0.5117
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8089 - loss: 0.4101 - val_accuracy: 0.7662 - val_loss: 0.5008
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8250 - loss: 0.3745 - val_accuracy: 0.7662 - val_loss: 0.5126
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8368 - loss: 0.3893 - val_accuracy: 0.7597 - val_loss: 0.5070
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8336 - loss: 0.3887 - val_accuracy: 0.7597 - val_loss: 0.5158
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8234 - loss: 0.4171 - val_accuracy: 0.7597 - val_loss: 0.5096
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8172 - loss: 0.4054 - val_accuracy: 0.7662 - val_loss: 0.5136
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8219 - loss: 0.4054 - val_accuracy: 0.7792 - val_loss: 0.5074
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8360 - loss: 0.4094 - val_accuracy: 0.7597 - val_loss: 0.5201
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8389 - loss: 0.4001 - val_accuracy: 0.7727 - val_loss: 0.5157
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8366 - loss: 0.3867 - val_accuracy: 0.7468 - val_loss: 0.5238
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8481 - loss: 0.3599 - val_accuracy: 0.7597 - val_loss: 0.5132
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8345 - loss: 0.3837 - val_accuracy: 0.7597 - val_loss: 0.5223
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8547 - loss: 0.3419 - val_accuracy: 0.7662 - val_loss: 0.5133
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8512 - loss: 0.3368 - val_accuracy: 0.7792 - val_loss: 0.5151
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8645 - loss: 0.3376 - val_accuracy: 0.7662 - val_loss: 0.5222
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8390 - loss: 0.3664 - val_accuracy: 0.7468 - val_loss: 0.5537
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8246 - loss: 0.3635 - val_accuracy: 0.7662 - val_loss: 0.5341
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8384 - loss: 0.3515 - val_accuracy: 0.7727 - val_loss: 0.5155
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8393 - loss: 0.3588 - val_accuracy: 0.7597 - val_loss: 0.5188
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8504 - loss: 0.3547 - val_accuracy: 0.7662 - val_loss: 0.5290
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8557 - loss: 0.3417 - val_accuracy: 0.7597 - val_loss: 0.5242
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8591 - loss: 0.3456 - val_accuracy: 0.7662 - val_loss: 0.5283
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8215 - loss: 0.3861 - val_accuracy: 0.7597 - val_loss: 0.5359
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8564 - loss: 0.3289 - val_accuracy: 0.7662 - val_loss: 0.5315
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8623 - loss: 0.3219 - val_accuracy: 0.7468 - val_loss: 0.5445
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8383 - loss: 0.3462 - val_accuracy: 0.7662 - val_loss: 0.5290
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8463 - loss: 0.3549 - val_accuracy: 0.7597 - val_loss: 0.5354
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8289 - loss: 0.3664 - val_accuracy: 0.7662 - val_loss: 0.5431
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8378 - loss: 0.3589 - val_accuracy: 0.7468 - val_loss: 0.5464
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8612 - loss: 0.3404 - val_accuracy: 0.7532 - val_loss: 0.5560
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8528 - loss: 0.3213 - val_accuracy: 0.7662 - val_loss: 0.5428
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8513 - loss: 0.3410 - val_accuracy: 0.7727 - val_loss: 0.5332
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8347 - loss: 0.3454 - val_accuracy: 0.7597 - val_loss: 0.5513
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8273 - loss: 0.3528 - val_accuracy: 0.7597 - val_loss: 0.5614
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8496 - loss: 0.3308 - val_accuracy: 0.7662 - val_loss: 0.5398
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8685 - loss: 0.3238 - val_accuracy: 0.7727 - val_loss: 0.5332
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8475 - loss: 0.3229 - val_accuracy: 0.7662 - val_loss: 0.5510
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8641 - loss: 0.3199 - val_accuracy: 0.7662 - val_loss: 0.5724
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8690 - loss: 0.2921 - val_accuracy: 0.7597 - val_loss: 0.5515
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8664 - loss: 0.3164 - val_accuracy: 0.7662 - val_loss: 0.5567
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8634 - loss: 0.3262 - val_accuracy: 0.7792 - val_loss: 0.5511
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8769 - loss: 0.3020 - val_accuracy: 0.7662 - val_loss: 0.5548
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8768 - loss: 0.2804 - val_accuracy: 0.7792 - val_loss: 0.5642
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3301 - val_accuracy: 0.7727 - val_loss: 0.5577
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8708 - loss: 0.2916 - val_accuracy: 0.7597 - val_loss: 0.5640
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8606 - loss: 0.3098 - val_accuracy: 0.7727 - val_loss: 0.5538
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8778 - loss: 0.2874 - val_accuracy: 0.7662 - val_loss: 0.5734
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8819 - loss: 0.3006 - val_accuracy: 0.7532 - val_loss: 0.5845
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8747 - loss: 0.2941 - val_accuracy: 0.7662 - val_loss: 0.5773
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8768 - loss: 0.2905 - val_accuracy: 0.7597 - val_loss: 0.5984
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8747 - loss: 0.2907 - val_accuracy: 0.7727 - val_loss: 0.5807
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8751 - loss: 0.2929 - val_accuracy: 0.7532 - val_loss: 0.5822
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8785 - loss: 0.2706 - val_accuracy: 0.7662 - val_loss: 0.5681
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8650 - loss: 0.2812 - val_accuracy: 0.7727 - val_loss: 0.5885
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8788 - loss: 0.2755 - val_accuracy: 0.7532 - val_loss: 0.5848
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8864 - loss: 0.2793 - val_accuracy: 0.7532 - val_loss: 0.5958
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8913 - loss: 0.2741 - val_accuracy: 0.7727 - val_loss: 0.5541
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8773 - loss: 0.2785 - val_accuracy: 0.7662 - val_loss: 0.5738
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8817 - loss: 0.2801 - val_accuracy: 0.7662 - val_loss: 0.5666
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8854 - loss: 0.2634 - val_accuracy: 0.7597 - val_loss: 0.5826
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9021 - loss: 0.2591 - val_accuracy: 0.7792 - val_loss: 0.5840
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8838 - loss: 0.2763 - val_accuracy: 0.7662 - val_loss: 0.5778
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8969 - loss: 0.2644 - val_accuracy: 0.7857 - val_loss: 0.5696
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8748 - loss: 0.2799 - val_accuracy: 0.7662 - val_loss: 0.5841
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8995 - loss: 0.2466 - val_accuracy: 0.7662 - val_loss: 0.5852
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8966 - loss: 0.2532 - val_accuracy: 0.7662 - val_loss: 0.5960
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9086 - loss: 0.2492 - val_accuracy: 0.7532 - val_loss: 0.6091
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9176 - loss: 0.2377 - val_accuracy: 0.7662 - val_loss: 0.5922
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8940 - loss: 0.2599 - val_accuracy: 0.7662 - val_loss: 0.6015
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9142 - loss: 0.2303 - val_accuracy: 0.7597 - val_loss: 0.6017
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8868 - loss: 0.2674 - val_accuracy: 0.7468 - val_loss: 0.6660
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8998 - loss: 0.2553 - val_accuracy: 0.7532 - val_loss: 0.6254
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9016 - loss: 0.2596 - val_accuracy: 0.7597 - val_loss: 0.6240

In [62]:
from keras.layers import Dropout

In [63]:
# all in one model

def build_model_all(hp):
  model = Sequential()
  counter = 0

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    if counter == 0:
      model.add(Dense(hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                      activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),
                      input_dim=8
                      ))
      model.add(Dropout(hp.Choice('dropout'+str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))

    else:
      model.add(Dense(hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                      activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),
      ))
      model.add(Dropout(hp.Choice('dropout'+str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))

    counter += 1

  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer = hp.Choice('optimizer', values=['rmsprop', 'adam', 'sgd', 'adadelta', 'nadam']),
                loss='binary_crossentropy',
                metrics=['accuracy'])

  return model

In [64]:
tuner = kt.RandomSearch(build_model_all,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name='num_layers_dropout')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [65]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 3 Complete [00h 00m 03s]
val_accuracy: 0.7337662577629089

Best val_accuracy So Far: 0.7337662577629089
Total elapsed time: 00h 00m 19s

In [66]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 1,
 'units0': 88,
 'activation0': 'relu',
 'dropout0': 0.9,
 'optimizer': 'sgd',
 'units1': 24,
 'activation1': 'relu',
 'dropout1': 0.1,
 'units2': 112,
 'activation2': 'sigmoid',
 'dropout2': 0.9,
 'units3': 24,
 'activation3': 'tanh',
 'dropout3': 0.8,
 'units4': 48,
 'activation4': 'relu',
 'dropout4': 0.6,
 'units5': 56,
 'activation5': 'sigmoid',
 'dropout5': 0.4,
 'units6': 16,
 'activation6': 'tanh',
 'dropout6': 0.2,
 'units7': 48,
 'activation7': 'relu',
 'dropout7': 0.5,
 'units8': 16,
 'activation8': 'relu',
 'dropout8': 0.5}

In [67]:
model = tuner.get_best_models(num_models=1)[0]

In [68]:
model.fit(X_train, y_train, epochs=200, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5721 - loss: 0.7449 - val_accuracy: 0.7338 - val_loss: 0.5879
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5611 - loss: 0.7150 - val_accuracy: 0.7338 - val_loss: 0.5785
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6505 - loss: 0.6313 - val_accuracy: 0.7403 - val_loss: 0.5701
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6464 - loss: 0.6593 - val_accuracy: 0.7532 - val_loss: 0.5623
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6453 - loss: 0.6530 - val_accuracy: 0.7532 - val_loss: 0.5560
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6884 - loss: 0.6099 - val_accuracy: 0.7597 - val_loss: 0.5518
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5984 - loss: 0.6792 - val_accuracy: 0.7727 - val_loss: 0.5464
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6712 - loss: 0.6179 - val_accuracy: 0.7662 - val_loss: 0.5418
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6476 - loss: 0.6198 - val_accuracy: 0.7662 - val_loss: 0.5378
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6887 - loss: 0.5858 - val_accuracy: 0.7597 - val_loss: 0.5339
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6493 - loss: 0.6291 - val_accuracy: 0.7532 - val_loss: 0.5311
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6725 - loss: 0.6080 - val_accuracy: 0.7468 - val_loss: 0.5272
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6611 - loss: 0.6255 - val_accuracy: 0.7468 - val_loss: 0.5244
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6927 - loss: 0.5954 - val_accuracy: 0.7532 - val_loss: 0.5220
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7226 - loss: 0.5598 - val_accuracy: 0.7597 - val_loss: 0.5191
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7161 - loss: 0.5721 - val_accuracy: 0.7597 - val_loss: 0.5172
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6820 - loss: 0.6091 - val_accuracy: 0.7532 - val_loss: 0.5154
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6999 - loss: 0.5938 - val_accuracy: 0.7532 - val_loss: 0.5139
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6691 - loss: 0.6153 - val_accuracy: 0.7532 - val_loss: 0.5116
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6925 - loss: 0.5940 - val_accuracy: 0.7532 - val_loss: 0.5110
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6856 - loss: 0.5902 - val_accuracy: 0.7532 - val_loss: 0.5099
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7206 - loss: 0.5708 - val_accuracy: 0.7532 - val_loss: 0.5080
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6931 - loss: 0.5789 - val_accuracy: 0.7597 - val_loss: 0.5071
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6531 - loss: 0.6254 - val_accuracy: 0.7597 - val_loss: 0.5062
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7140 - loss: 0.5429 - val_accuracy: 0.7597 - val_loss: 0.5048
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6633 - loss: 0.6109 - val_accuracy: 0.7792 - val_loss: 0.5042
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7009 - loss: 0.5592 - val_accuracy: 0.7857 - val_loss: 0.5027
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7275 - loss: 0.5524 - val_accuracy: 0.7922 - val_loss: 0.5022
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7309 - loss: 0.5462 - val_accuracy: 0.7922 - val_loss: 0.5008
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7207 - loss: 0.5513 - val_accuracy: 0.7922 - val_loss: 0.5002
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7282 - loss: 0.5229 - val_accuracy: 0.7922 - val_loss: 0.4999
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7156 - loss: 0.5626 - val_accuracy: 0.7922 - val_loss: 0.4992
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7173 - loss: 0.5525 - val_accuracy: 0.7922 - val_loss: 0.4979
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7519 - loss: 0.5162 - val_accuracy: 0.7922 - val_loss: 0.4972
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7219 - loss: 0.5326 - val_accuracy: 0.7922 - val_loss: 0.4962
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7289 - loss: 0.5445 - val_accuracy: 0.7922 - val_loss: 0.4956
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7382 - loss: 0.5449 - val_accuracy: 0.7987 - val_loss: 0.4950
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6921 - loss: 0.5801 - val_accuracy: 0.8052 - val_loss: 0.4943
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6877 - loss: 0.5707 - val_accuracy: 0.7987 - val_loss: 0.4940
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7191 - loss: 0.5497 - val_accuracy: 0.8052 - val_loss: 0.4936
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6876 - loss: 0.5623 - val_accuracy: 0.8052 - val_loss: 0.4929
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6615 - loss: 0.6051 - val_accuracy: 0.8052 - val_loss: 0.4925
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7203 - loss: 0.5588 - val_accuracy: 0.8052 - val_loss: 0.4926
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7192 - loss: 0.5326 - val_accuracy: 0.8052 - val_loss: 0.4922
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5263 - val_accuracy: 0.8052 - val_loss: 0.4916
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7137 - loss: 0.5702 - val_accuracy: 0.7922 - val_loss: 0.4916
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7461 - loss: 0.5223 - val_accuracy: 0.7987 - val_loss: 0.4910
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7139 - loss: 0.5674 - val_accuracy: 0.8052 - val_loss: 0.4901
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7307 - loss: 0.5444 - val_accuracy: 0.8052 - val_loss: 0.4899
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6839 - loss: 0.5652 - val_accuracy: 0.8052 - val_loss: 0.4898
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6887 - loss: 0.5679 - val_accuracy: 0.8052 - val_loss: 0.4891
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7249 - loss: 0.5684 - val_accuracy: 0.8052 - val_loss: 0.4887
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7212 - loss: 0.5244 - val_accuracy: 0.8052 - val_loss: 0.4886
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7169 - loss: 0.5563 - val_accuracy: 0.7987 - val_loss: 0.4890
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7351 - loss: 0.5161 - val_accuracy: 0.7987 - val_loss: 0.4892
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7574 - loss: 0.4978 - val_accuracy: 0.7922 - val_loss: 0.4883
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7157 - loss: 0.5507 - val_accuracy: 0.7922 - val_loss: 0.4878
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7401 - loss: 0.4998 - val_accuracy: 0.7987 - val_loss: 0.4873
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7032 - loss: 0.5272 - val_accuracy: 0.7987 - val_loss: 0.4867
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7056 - loss: 0.5627 - val_accuracy: 0.7922 - val_loss: 0.4864
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7209 - loss: 0.5301 - val_accuracy: 0.7922 - val_loss: 0.4862
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7291 - loss: 0.5258 - val_accuracy: 0.7922 - val_loss: 0.4862
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7168 - loss: 0.5143 - val_accuracy: 0.7922 - val_loss: 0.4859
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6910 - loss: 0.5520 - val_accuracy: 0.7922 - val_loss: 0.4865
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7562 - loss: 0.5012 - val_accuracy: 0.7987 - val_loss: 0.4865
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7571 - loss: 0.5127 - val_accuracy: 0.7922 - val_loss: 0.4860
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7247 - loss: 0.5442 - val_accuracy: 0.7987 - val_loss: 0.4861
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7157 - loss: 0.5389 - val_accuracy: 0.8052 - val_loss: 0.4855
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7353 - loss: 0.5321 - val_accuracy: 0.7987 - val_loss: 0.4852
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7095 - loss: 0.5222 - val_accuracy: 0.7987 - val_loss: 0.4852
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7300 - loss: 0.5248 - val_accuracy: 0.7987 - val_loss: 0.4851
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7348 - loss: 0.5157 - val_accuracy: 0.7922 - val_loss: 0.4852
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7109 - loss: 0.5312 - val_accuracy: 0.8052 - val_loss: 0.4849
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7334 - loss: 0.5042 - val_accuracy: 0.7922 - val_loss: 0.4850
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6996 - loss: 0.5559 - val_accuracy: 0.7857 - val_loss: 0.4844
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7467 - loss: 0.5096 - val_accuracy: 0.7987 - val_loss: 0.4836
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7254 - loss: 0.5145 - val_accuracy: 0.7922 - val_loss: 0.4837
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7313 - loss: 0.5396 - val_accuracy: 0.7987 - val_loss: 0.4833
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7196 - loss: 0.5225 - val_accuracy: 0.7987 - val_loss: 0.4826
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7409 - loss: 0.5226 - val_accuracy: 0.7922 - val_loss: 0.4825
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7390 - loss: 0.4866 - val_accuracy: 0.7922 - val_loss: 0.4827
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7808 - loss: 0.4792 - val_accuracy: 0.7922 - val_loss: 0.4826
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7232 - loss: 0.5382 - val_accuracy: 0.7922 - val_loss: 0.4829
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7127 - loss: 0.5202 - val_accuracy: 0.7857 - val_loss: 0.4826
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7393 - loss: 0.5465 - val_accuracy: 0.7857 - val_loss: 0.4831
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7364 - loss: 0.5172 - val_accuracy: 0.7857 - val_loss: 0.4828
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7355 - loss: 0.5513 - val_accuracy: 0.7857 - val_loss: 0.4830
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7340 - loss: 0.5280 - val_accuracy: 0.7857 - val_loss: 0.4833
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7278 - loss: 0.5368 - val_accuracy: 0.7922 - val_loss: 0.4833
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7016 - loss: 0.5427 - val_accuracy: 0.7987 - val_loss: 0.4832
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7195 - loss: 0.5542 - val_accuracy: 0.7922 - val_loss: 0.4829
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4792 - val_accuracy: 0.7922 - val_loss: 0.4824
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7545 - loss: 0.4968 - val_accuracy: 0.7857 - val_loss: 0.4822
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7255 - loss: 0.5311 - val_accuracy: 0.7857 - val_loss: 0.4829
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7368 - loss: 0.5392 - val_accuracy: 0.7857 - val_loss: 0.4829
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7232 - loss: 0.5107 - val_accuracy: 0.7922 - val_loss: 0.4838
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7574 - loss: 0.4975 - val_accuracy: 0.7857 - val_loss: 0.4835
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7293 - loss: 0.5249 - val_accuracy: 0.7857 - val_loss: 0.4834
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7390 - loss: 0.5081 - val_accuracy: 0.7857 - val_loss: 0.4829
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7540 - loss: 0.4835 - val_accuracy: 0.7857 - val_loss: 0.4825
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7186 - loss: 0.5314 - val_accuracy: 0.7857 - val_loss: 0.4822
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7362 - loss: 0.5097 - val_accuracy: 0.7922 - val_loss: 0.4824
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7414 - loss: 0.5172 - val_accuracy: 0.7987 - val_loss: 0.4824
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7252 - loss: 0.5136 - val_accuracy: 0.7987 - val_loss: 0.4822
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7406 - loss: 0.5274 - val_accuracy: 0.7987 - val_loss: 0.4817
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7223 - loss: 0.5336 - val_accuracy: 0.7987 - val_loss: 0.4817
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7204 - loss: 0.5312 - val_accuracy: 0.7922 - val_loss: 0.4818
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7283 - loss: 0.5161 - val_accuracy: 0.7922 - val_loss: 0.4817
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7639 - loss: 0.5021 - val_accuracy: 0.7857 - val_loss: 0.4810
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7475 - loss: 0.5143 - val_accuracy: 0.7857 - val_loss: 0.4809
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7358 - loss: 0.4991 - val_accuracy: 0.7857 - val_loss: 0.4811
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7126 - loss: 0.5421 - val_accuracy: 0.7857 - val_loss: 0.4808
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7203 - loss: 0.5281 - val_accuracy: 0.7857 - val_loss: 0.4807
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7624 - loss: 0.5123 - val_accuracy: 0.7857 - val_loss: 0.4809
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7084 - loss: 0.5776 - val_accuracy: 0.7857 - val_loss: 0.4809
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7612 - loss: 0.4888 - val_accuracy: 0.7857 - val_loss: 0.4810
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7173 - loss: 0.5320 - val_accuracy: 0.7857 - val_loss: 0.4815
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7346 - loss: 0.5024 - val_accuracy: 0.7857 - val_loss: 0.4817
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7325 - loss: 0.4898 - val_accuracy: 0.7857 - val_loss: 0.4814
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7456 - loss: 0.4832 - val_accuracy: 0.7857 - val_loss: 0.4813
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7333 - loss: 0.5049 - val_accuracy: 0.7857 - val_loss: 0.4814
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7314 - loss: 0.5336 - val_accuracy: 0.7857 - val_loss: 0.4817
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7596 - loss: 0.4867 - val_accuracy: 0.7857 - val_loss: 0.4820
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7349 - loss: 0.5145 - val_accuracy: 0.7857 - val_loss: 0.4817
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7181 - loss: 0.5125 - val_accuracy: 0.7857 - val_loss: 0.4817
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7579 - loss: 0.4813 - val_accuracy: 0.7857 - val_loss: 0.4816
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7520 - loss: 0.4802 - val_accuracy: 0.7857 - val_loss: 0.4814
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7511 - loss: 0.5129 - val_accuracy: 0.7792 - val_loss: 0.4812
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7311 - loss: 0.5303 - val_accuracy: 0.7792 - val_loss: 0.4806
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5122 - val_accuracy: 0.7792 - val_loss: 0.4801
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7711 - loss: 0.4818 - val_accuracy: 0.7792 - val_loss: 0.4804
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7372 - loss: 0.4946 - val_accuracy: 0.7792 - val_loss: 0.4802
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4963 - val_accuracy: 0.7792 - val_loss: 0.4802
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7645 - loss: 0.4876 - val_accuracy: 0.7792 - val_loss: 0.4802
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7293 - loss: 0.5185 - val_accuracy: 0.7792 - val_loss: 0.4808
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7491 - loss: 0.4818 - val_accuracy: 0.7792 - val_loss: 0.4806
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7734 - loss: 0.4961 - val_accuracy: 0.7792 - val_loss: 0.4803
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.4990 - val_accuracy: 0.7792 - val_loss: 0.4803
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7313 - loss: 0.5062 - val_accuracy: 0.7792 - val_loss: 0.4802
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4970 - val_accuracy: 0.7792 - val_loss: 0.4797
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7250 - loss: 0.5180 - val_accuracy: 0.7792 - val_loss: 0.4797
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7386 - loss: 0.5013 - val_accuracy: 0.7792 - val_loss: 0.4794
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7107 - loss: 0.5367 - val_accuracy: 0.7922 - val_loss: 0.4797
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7486 - loss: 0.5244 - val_accuracy: 0.7792 - val_loss: 0.4798
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7354 - loss: 0.4966 - val_accuracy: 0.7857 - val_loss: 0.4795
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7123 - loss: 0.5407 - val_accuracy: 0.7857 - val_loss: 0.4796
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7569 - loss: 0.4920 - val_accuracy: 0.7857 - val_loss: 0.4797
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7069 - loss: 0.5448 - val_accuracy: 0.7857 - val_loss: 0.4800
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7523 - loss: 0.5218 - val_accuracy: 0.7857 - val_loss: 0.4798
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7684 - loss: 0.4838 - val_accuracy: 0.7922 - val_loss: 0.4801
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7604 - loss: 0.4963 - val_accuracy: 0.7922 - val_loss: 0.4797
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4891 - val_accuracy: 0.7857 - val_loss: 0.4800
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7352 - loss: 0.5030 - val_accuracy: 0.7792 - val_loss: 0.4803
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7593 - loss: 0.5096 - val_accuracy: 0.7792 - val_loss: 0.4806
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7377 - loss: 0.5183 - val_accuracy: 0.7792 - val_loss: 0.4810
Epoch 162/200