<a href="https://colab.research.google.com/github/SakshiKhatiwada/Python/blob/main/Deep-Learning/keras_hyperparameter_tuning_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("diabetes.csv")

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [7]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [9]:
X = scaler.fit_transform(X)

In [10]:
X.shape

(768, 8)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=52 )

In [12]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [13]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
model.fit(X_train, y_train, batch_size= 32, epochs = 100, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.5796 - loss: 0.7142 - val_accuracy: 0.6948 - val_loss: 0.6154
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6687 - loss: 0.6456 - val_accuracy: 0.7338 - val_loss: 0.5769
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6955 - loss: 0.6008 - val_accuracy: 0.7597 - val_loss: 0.5483
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7148 - loss: 0.5711 - val_accuracy: 0.7532 - val_loss: 0.5249
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7390 - loss: 0.5479 - val_accuracy: 0.7727 - val_loss: 0.5104
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7258 - loss: 0.5408 - val_accuracy: 0.7857 - val_loss: 0.5004
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7442 - loss: 0.5268 - val_accuracy: 0.7857 - val_loss: 0.4907
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7576 - loss: 0.5074 - val_accuracy: 0.7857 - val_loss: 0.4834
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7574 - loss: 0.4979 - val_accuracy: 0.7857 - val_loss: 0.4788
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7823 - loss: 0.4810 - val_accuracy: 0.7857 - val_loss: 0.4739
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7602 - loss: 0.4942 - val_accuracy: 0.7857 - val_loss: 0.4713
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7885 - loss: 0.4633 - val_accuracy: 0.7987 - val_loss: 0.4697
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7646 - loss: 0.4774 - val_accuracy: 0.7922 - val_loss: 0.4697
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7764 - loss: 0.4663 - val_accuracy: 0.7922 - val_loss: 0.4688
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4544 - val_accuracy: 0.7857 - val_loss: 0.4689
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7734 - loss: 0.4710 - val_accuracy: 0.7857 - val_loss: 0.4685
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7543 - loss: 0.4747 - val_accuracy: 0.7857 - val_loss: 0.4690
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7659 - loss: 0.4692 - val_accuracy: 0.7857 - val_loss: 0.4682
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7676 - loss: 0.4648 - val_accuracy: 0.7857 - val_loss: 0.4694
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7886 - loss: 0.4258 - val_accuracy: 0.7792 - val_loss: 0.4695
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7647 - loss: 0.4551 - val_accuracy: 0.7792 - val_loss: 0.4700
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4344 - val_accuracy: 0.7792 - val_loss: 0.4703
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7735 - loss: 0.4648 - val_accuracy: 0.7857 - val_loss: 0.4706
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8066 - loss: 0.4261 - val_accuracy: 0.7857 - val_loss: 0.4726
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7936 - loss: 0.4399 - val_accuracy: 0.7792 - val_loss: 0.4731
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7954 - loss: 0.4231 - val_accuracy: 0.7857 - val_loss: 0.4737
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7966 - loss: 0.4410 - val_accuracy: 0.7857 - val_loss: 0.4749
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7738 - loss: 0.4596 - val_accuracy: 0.7857 - val_loss: 0.4747
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7873 - loss: 0.4403 - val_accuracy: 0.7857 - val_loss: 0.4745
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7758 - loss: 0.4472 - val_accuracy: 0.7922 - val_loss: 0.4741
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8215 - loss: 0.4084 - val_accuracy: 0.7792 - val_loss: 0.4746
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4228 - val_accuracy: 0.7727 - val_loss: 0.4753
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7902 - loss: 0.4304 - val_accuracy: 0.7727 - val_loss: 0.4761
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7919 - loss: 0.4308 - val_accuracy: 0.7727 - val_loss: 0.4782
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7787 - loss: 0.4551 - val_accuracy: 0.7662 - val_loss: 0.4792
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7894 - loss: 0.4406 - val_accuracy: 0.7597 - val_loss: 0.4804
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7967 - loss: 0.4196 - val_accuracy: 0.7662 - val_loss: 0.4803
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8248 - loss: 0.4052 - val_accuracy: 0.7662 - val_loss: 0.4790
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7847 - loss: 0.4344 - val_accuracy: 0.7662 - val_loss: 0.4782
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7903 - loss: 0.4304 - val_accuracy: 0.7662 - val_loss: 0.4784
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7995 - loss: 0.4242 - val_accuracy: 0.7662 - val_loss: 0.4798
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8156 - loss: 0.4211 - val_accuracy: 0.7597 - val_loss: 0.4820
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8309 - loss: 0.3906 - val_accuracy: 0.7597 - val_loss: 0.4827
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8090 - loss: 0.4173 - val_accuracy: 0.7662 - val_loss: 0.4803
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8097 - loss: 0.4133 - val_accuracy: 0.7662 - val_loss: 0.4779
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7827 - loss: 0.4488 - val_accuracy: 0.7532 - val_loss: 0.4812
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8096 - loss: 0.4101 - val_accuracy: 0.7597 - val_loss: 0.4800
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8161 - loss: 0.4064 - val_accuracy: 0.7597 - val_loss: 0.4812
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7778 - loss: 0.4468 - val_accuracy: 0.7532 - val_loss: 0.4820
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8022 - loss: 0.4319 - val_accuracy: 0.7532 - val_loss: 0.4834
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8045 - loss: 0.4131 - val_accuracy: 0.7597 - val_loss: 0.4820
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8057 - loss: 0.4248 - val_accuracy: 0.7532 - val_loss: 0.4839
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8276 - loss: 0.4021 - val_accuracy: 0.7597 - val_loss: 0.4846
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8316 - loss: 0.3995 - val_accuracy: 0.7532 - val_loss: 0.4857
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8026 - loss: 0.4110 - val_accuracy: 0.7662 - val_loss: 0.4842
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8079 - loss: 0.4241 - val_accuracy: 0.7662 - val_loss: 0.4855
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7895 - loss: 0.4469 - val_accuracy: 0.7597 - val_loss: 0.4860
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8209 - loss: 0.4006 - val_accuracy: 0.7597 - val_loss: 0.4858
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8105 - loss: 0.4031 - val_accuracy: 0.7597 - val_loss: 0.4867
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8126 - loss: 0.4276 - val_accuracy: 0.7532 - val_loss: 0.4869
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8219 - loss: 0.4057 - val_accuracy: 0.7532 - val_loss: 0.4872
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8222 - loss: 0.4033 - val_accuracy: 0.7532 - val_loss: 0.4870
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8038 - loss: 0.4335 - val_accuracy: 0.7532 - val_loss: 0.4890
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8069 - loss: 0.4416 - val_accuracy: 0.7532 - val_loss: 0.4878
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8179 - loss: 0.3963 - val_accuracy: 0.7597 - val_loss: 0.4853
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8087 - loss: 0.4176 - val_accuracy: 0.7597 - val_loss: 0.4868
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8195 - loss: 0.3990 - val_accuracy: 0.7468 - val_loss: 0.4887
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8183 - loss: 0.4068 - val_accuracy: 0.7597 - val_loss: 0.4873
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8132 - loss: 0.4289 - val_accuracy: 0.7597 - val_loss: 0.4881
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8298 - loss: 0.4026 - val_accuracy: 0.7597 - val_loss: 0.4880
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8418 - loss: 0.3804 - val_accuracy: 0.7532 - val_loss: 0.4900
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8314 - loss: 0.3934 - val_accuracy: 0.7597 - val_loss: 0.4907
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8361 - loss: 0.3995 - val_accuracy: 0.7597 - val_loss: 0.4921
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8145 - loss: 0.4114 - val_accuracy: 0.7597 - val_loss: 0.4919
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8197 - loss: 0.4220 - val_accuracy: 0.7597 - val_loss: 0.4931
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.8084 - loss: 0.4287 - val_accuracy: 0.7597 - val_loss: 0.4925
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.8065 - loss: 0.4163 - val_accuracy: 0.7597 - val_loss: 0.4903
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8299 - loss: 0.4009 - val_accuracy: 0.7597 - val_loss: 0.4913
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.8437 - loss: 0.3659 - val_accuracy: 0.7532 - val_loss: 0.4945
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8177 - loss: 0.4052 - val_accuracy: 0.7532 - val_loss: 0.4953
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8219 - loss: 0.3917 - val_accuracy: 0.7468 - val_loss: 0.4958
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8250 - loss: 0.4083 - val_accuracy: 0.7532 - val_loss: 0.4940
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8300 - loss: 0.3927 - val_accuracy: 0.7597 - val_loss: 0.4936
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8196 - loss: 0.3902 - val_accuracy: 0.7532 - val_loss: 0.4956
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8126 - loss: 0.4166 - val_accuracy: 0.7468 - val_loss: 0.4956
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8126 - loss: 0.4038 - val_accuracy: 0.7597 - val_loss: 0.4936
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8181 - loss: 0.4079 - val_accuracy: 0.7597 - val_loss: 0.4928
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8395 - loss: 0.3773 - val_accuracy: 0.7597 - val_loss: 0.4917
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7765 - loss: 0.4272 - val_accuracy: 0.7597 - val_loss: 0.4942
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8145 - loss: 0.4069 - val_accuracy: 0.7597 - val_loss: 0.4939
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8391 - loss: 0.3784 - val_accuracy: 0.7468 - val_loss: 0.4969
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8394 - loss: 0.3881 - val_accuracy: 0.7532 - val_loss: 0.4964
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8228 - loss: 0.3840 - val_accuracy: 0.7468 - val_loss: 0.4970
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8384 - loss: 0.3690 - val_accuracy: 0.7532 - val_loss: 0.4952
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8413 - loss: 0.3747 - val_accuracy: 0.7468 - val_loss: 0.4946
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8114 - loss: 0.4120 - val_accuracy: 0.7532 - val_loss: 0.4962
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8133 - loss: 0.4019 - val_accuracy: 0.7532 - val_loss: 0.4960
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8488 - loss: 0.3670 - val_accuracy: 0.7468 - val_loss: 0.4985
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8265 - loss: 0.3971 - val_accuracy: 0.7597 - val_loss: 0.4934
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8312 - loss: 0.4046 - val_accuracy: 0.7597 - val_loss: 0.4917

In [17]:
!pip install -U keras-tuner
import kerastuner as kt

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (25.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.15.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.17.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2025.10.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras->keras-tuner) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 3.7 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

/tmp/ipython-input-3209566528.py:2: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [18]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta'])
  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [19]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5
    )

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [20]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test, y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7272727489471436

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 00m 11s

In [22]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [23]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [25]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 58ms/step - accuracy: 0.8375 - loss: 0.3676 - val_accuracy: 0.7597 - val_loss: 0.5068
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.8106 - loss: 0.4252 - val_accuracy: 0.7662 - val_loss: 0.5083
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.8374 - loss: 0.3890 - val_accuracy: 0.7597 - val_loss: 0.5094
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.8114 - loss: 0.4128 - val_accuracy: 0.7532 - val_loss: 0.5087
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8281 - loss: 0.4030 - val_accuracy: 0.7662 - val_loss: 0.5107
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8146 - loss: 0.4128 - val_accuracy: 0.7597 - val_loss: 0.5109
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8220 - loss: 0.3921 - val_accuracy: 0.7597 - val_loss: 0.5112
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8233 - loss: 0.4111 - val_accuracy: 0.7532 - val_loss: 0.5102
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8266 - loss: 0.3996 - val_accuracy: 0.7532 - val_loss: 0.5099
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8316 - loss: 0.3956 - val_accuracy: 0.7532 - val_loss: 0.5106
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8140 - loss: 0.4210 - val_accuracy: 0.7532 - val_loss: 0.5113
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8344 - loss: 0.3801 - val_accuracy: 0.7532 - val_loss: 0.5098
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8055 - loss: 0.4134 - val_accuracy: 0.7597 - val_loss: 0.5113
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8204 - loss: 0.3945 - val_accuracy: 0.7597 - val_loss: 0.5116
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8113 - loss: 0.4023 - val_accuracy: 0.7597 - val_loss: 0.5127
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8234 - loss: 0.4010 - val_accuracy: 0.7597 - val_loss: 0.5132
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8350 - loss: 0.3930 - val_accuracy: 0.7532 - val_loss: 0.5131
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8390 - loss: 0.3705 - val_accuracy: 0.7532 - val_loss: 0.5111
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8449 - loss: 0.3775 - val_accuracy: 0.7532 - val_loss: 0.5096
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8233 - loss: 0.3843 - val_accuracy: 0.7532 - val_loss: 0.5114
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8135 - loss: 0.4060 - val_accuracy: 0.7532 - val_loss: 0.5101
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8217 - loss: 0.3958 - val_accuracy: 0.7532 - val_loss: 0.5125
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8253 - loss: 0.4177 - val_accuracy: 0.7532 - val_loss: 0.5105
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8273 - loss: 0.3802 - val_accuracy: 0.7597 - val_loss: 0.5109
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4032 - val_accuracy: 0.7597 - val_loss: 0.5118
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8157 - loss: 0.4110 - val_accuracy: 0.7532 - val_loss: 0.5114
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8319 - loss: 0.3922 - val_accuracy: 0.7532 - val_loss: 0.5147
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8024 - loss: 0.3995 - val_accuracy: 0.7532 - val_loss: 0.5121
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8463 - loss: 0.3635 - val_accuracy: 0.7532 - val_loss: 0.5120
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8315 - loss: 0.3727 - val_accuracy: 0.7532 - val_loss: 0.5148
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8177 - loss: 0.4284 - val_accuracy: 0.7532 - val_loss: 0.5144
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8211 - loss: 0.3939 - val_accuracy: 0.7532 - val_loss: 0.5132
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8228 - loss: 0.3823 - val_accuracy: 0.7532 - val_loss: 0.5137
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8235 - loss: 0.3851 - val_accuracy: 0.7532 - val_loss: 0.5148
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8316 - loss: 0.3780 - val_accuracy: 0.7532 - val_loss: 0.5150
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8115 - loss: 0.4098 - val_accuracy: 0.7468 - val_loss: 0.5148
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8108 - loss: 0.4150 - val_accuracy: 0.7532 - val_loss: 0.5138
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7930 - loss: 0.4128 - val_accuracy: 0.7532 - val_loss: 0.5136
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8333 - loss: 0.3764 - val_accuracy: 0.7532 - val_loss: 0.5137
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8264 - loss: 0.3951 - val_accuracy: 0.7468 - val_loss: 0.5159
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8348 - loss: 0.3796 - val_accuracy: 0.7468 - val_loss: 0.5161
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8164 - loss: 0.3867 - val_accuracy: 0.7532 - val_loss: 0.5160
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8052 - loss: 0.4140 - val_accuracy: 0.7468 - val_loss: 0.5157
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8297 - loss: 0.4027 - val_accuracy: 0.7532 - val_loss: 0.5150
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8267 - loss: 0.4075 - val_accuracy: 0.7597 - val_loss: 0.5138
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8296 - loss: 0.3777 - val_accuracy: 0.7468 - val_loss: 0.5149
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4119 - val_accuracy: 0.7468 - val_loss: 0.5158
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8395 - loss: 0.3951 - val_accuracy: 0.7532 - val_loss: 0.5155
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8377 - loss: 0.3793 - val_accuracy: 0.7468 - val_loss: 0.5175
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8361 - loss: 0.3873 - val_accuracy: 0.7532 - val_loss: 0.5184
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8482 - loss: 0.3710 - val_accuracy: 0.7597 - val_loss: 0.5185
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8099 - loss: 0.3935 - val_accuracy: 0.7597 - val_loss: 0.5187
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8147 - loss: 0.4129 - val_accuracy: 0.7468 - val_loss: 0.5171
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8231 - loss: 0.3862 - val_accuracy: 0.7468 - val_loss: 0.5168
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8378 - loss: 0.3794 - val_accuracy: 0.7468 - val_loss: 0.5180
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8361 - loss: 0.3802 - val_accuracy: 0.7468 - val_loss: 0.5183
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8488 - loss: 0.3643 - val_accuracy: 0.7468 - val_loss: 0.5183
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8486 - loss: 0.3705 - val_accuracy: 0.7468 - val_loss: 0.5208
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8365 - loss: 0.3615 - val_accuracy: 0.7532 - val_loss: 0.5199
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8199 - loss: 0.4186 - val_accuracy: 0.7532 - val_loss: 0.5196
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8542 - loss: 0.3688 - val_accuracy: 0.7532 - val_loss: 0.5213
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8369 - loss: 0.3791 - val_accuracy: 0.7468 - val_loss: 0.5208
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8348 - loss: 0.3794 - val_accuracy: 0.7468 - val_loss: 0.5193
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8282 - loss: 0.3755 - val_accuracy: 0.7468 - val_loss: 0.5193
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8334 - loss: 0.3887 - val_accuracy: 0.7532 - val_loss: 0.5190
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8388 - loss: 0.3785 - val_accuracy: 0.7532 - val_loss: 0.5203
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8272 - loss: 0.3835 - val_accuracy: 0.7532 - val_loss: 0.5205
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8326 - loss: 0.3652 - val_accuracy: 0.7532 - val_loss: 0.5207
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8348 - loss: 0.3880 - val_accuracy: 0.7532 - val_loss: 0.5211
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8268 - loss: 0.3895 - val_accuracy: 0.7468 - val_loss: 0.5215
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8344 - loss: 0.4021 - val_accuracy: 0.7532 - val_loss: 0.5214
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4344 - val_accuracy: 0.7532 - val_loss: 0.5205
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8517 - loss: 0.3656 - val_accuracy: 0.7468 - val_loss: 0.5216
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8225 - loss: 0.3936 - val_accuracy: 0.7532 - val_loss: 0.5197
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8478 - loss: 0.3709 - val_accuracy: 0.7597 - val_loss: 0.5209
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8256 - loss: 0.3855 - val_accuracy: 0.7597 - val_loss: 0.5211
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8355 - loss: 0.3719 - val_accuracy: 0.7468 - val_loss: 0.5194
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8151 - loss: 0.3868 - val_accuracy: 0.7532 - val_loss: 0.5208
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8496 - loss: 0.3540 - val_accuracy: 0.7468 - val_loss: 0.5208
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8212 - loss: 0.3986 - val_accuracy: 0.7532 - val_loss: 0.5223
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8301 - loss: 0.3790 - val_accuracy: 0.7532 - val_loss: 0.5222
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3761 - val_accuracy: 0.7597 - val_loss: 0.5214
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8426 - loss: 0.3674 - val_accuracy: 0.7597 - val_loss: 0.5232
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8414 - loss: 0.3765 - val_accuracy: 0.7532 - val_loss: 0.5263
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8253 - loss: 0.3695 - val_accuracy: 0.7532 - val_loss: 0.5250
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8578 - loss: 0.3490 - val_accuracy: 0.7597 - val_loss: 0.5228
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8202 - loss: 0.4026 - val_accuracy: 0.7532 - val_loss: 0.5239
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8233 - loss: 0.3808 - val_accuracy: 0.7532 - val_loss: 0.5240
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8610 - loss: 0.3549 - val_accuracy: 0.7532 - val_loss: 0.5230
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8316 - loss: 0.3743 - val_accuracy: 0.7597 - val_loss: 0.5234
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8461 - loss: 0.3554 - val_accuracy: 0.7597 - val_loss: 0.5241
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8414 - loss: 0.3814 - val_accuracy: 0.7662 - val_loss: 0.5222
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8312 - loss: 0.3651 - val_accuracy: 0.7662 - val_loss: 0.5210
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8339 - loss: 0.3896 - val_accuracy: 0.7662 - val_loss: 0.5234

In [34]:
# to find the optimal no. of nodes

def build_model2(hp):

  model = Sequential()
  units = hp.Int('units', min_value=8, max_value=128, step=8) # lower and upper limit, step size
  model.add(Dense(units = units, activation='relu', input_dim = 8))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [38]:
tuner = kt.RandomSearch(build_model2, objective='val_accuracy', max_trials=5,
                        directory='mydir')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [39]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.7337662577629089

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 14s

In [40]:
tuner.get_best_hyperparameters()[0].values

{'units': 120}

In [41]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [42]:
model.fit(X_train, y_train, batch_size=32, epochs = 100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.7960 - loss: 0.4816 - val_accuracy: 0.7987 - val_loss: 0.4760
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7822 - loss: 0.4522 - val_accuracy: 0.7922 - val_loss: 0.4770
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7904 - loss: 0.4499 - val_accuracy: 0.7792 - val_loss: 0.4750
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7930 - loss: 0.4537 - val_accuracy: 0.7792 - val_loss: 0.4719
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4349 - val_accuracy: 0.7792 - val_loss: 0.4740
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8047 - loss: 0.4232 - val_accuracy: 0.7792 - val_loss: 0.4737
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7953 - loss: 0.4477 - val_accuracy: 0.7727 - val_loss: 0.4746
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8019 - loss: 0.4401 - val_accuracy: 0.7727 - val_loss: 0.4783
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7959 - loss: 0.4259 - val_accuracy: 0.7727 - val_loss: 0.4767
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7903 - loss: 0.4375 - val_accuracy: 0.7727 - val_loss: 0.4774
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7839 - loss: 0.4448 - val_accuracy: 0.7727 - val_loss: 0.4781
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7875 - loss: 0.4277 - val_accuracy: 0.7662 - val_loss: 0.4813
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7815 - loss: 0.4549 - val_accuracy: 0.7662 - val_loss: 0.4826
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7973 - loss: 0.4172 - val_accuracy: 0.7662 - val_loss: 0.4834
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8052 - loss: 0.4157 - val_accuracy: 0.7662 - val_loss: 0.4803
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8076 - loss: 0.4413 - val_accuracy: 0.7662 - val_loss: 0.4791
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7860 - loss: 0.4522 - val_accuracy: 0.7727 - val_loss: 0.4796
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7905 - loss: 0.4268 - val_accuracy: 0.7727 - val_loss: 0.4811
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7914 - loss: 0.4374 - val_accuracy: 0.7662 - val_loss: 0.4791
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8076 - loss: 0.4100 - val_accuracy: 0.7597 - val_loss: 0.4830
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7858 - loss: 0.4367 - val_accuracy: 0.7532 - val_loss: 0.4875
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7793 - loss: 0.4395 - val_accuracy: 0.7662 - val_loss: 0.4855
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8259 - loss: 0.4000 - val_accuracy: 0.7662 - val_loss: 0.4834
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7777 - loss: 0.4463 - val_accuracy: 0.7532 - val_loss: 0.4837
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7689 - loss: 0.4357 - val_accuracy: 0.7532 - val_loss: 0.4836
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7771 - loss: 0.4281 - val_accuracy: 0.7792 - val_loss: 0.4805
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7893 - loss: 0.4233 - val_accuracy: 0.7727 - val_loss: 0.4839
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8150 - loss: 0.4369 - val_accuracy: 0.7532 - val_loss: 0.4864
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8217 - loss: 0.3976 - val_accuracy: 0.7662 - val_loss: 0.4845
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7992 - loss: 0.4283 - val_accuracy: 0.7792 - val_loss: 0.4840
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8259 - loss: 0.3983 - val_accuracy: 0.7727 - val_loss: 0.4830
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7939 - loss: 0.4188 - val_accuracy: 0.7727 - val_loss: 0.4871
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8069 - loss: 0.4017 - val_accuracy: 0.7792 - val_loss: 0.4851
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7898 - loss: 0.4319 - val_accuracy: 0.7727 - val_loss: 0.4862
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8197 - loss: 0.3983 - val_accuracy: 0.7662 - val_loss: 0.4871
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7945 - loss: 0.4231 - val_accuracy: 0.7597 - val_loss: 0.4844
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7881 - loss: 0.4362 - val_accuracy: 0.7727 - val_loss: 0.4838
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8041 - loss: 0.4214 - val_accuracy: 0.7727 - val_loss: 0.4843
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8015 - loss: 0.4059 - val_accuracy: 0.7727 - val_loss: 0.4859
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7982 - loss: 0.4192 - val_accuracy: 0.7857 - val_loss: 0.4861
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8008 - loss: 0.4095 - val_accuracy: 0.7857 - val_loss: 0.4868
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3896 - val_accuracy: 0.7792 - val_loss: 0.4843
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8100 - loss: 0.4090 - val_accuracy: 0.7727 - val_loss: 0.4865
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4098 - val_accuracy: 0.7727 - val_loss: 0.4859
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8171 - loss: 0.4031 - val_accuracy: 0.7727 - val_loss: 0.4873
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8314 - loss: 0.3805 - val_accuracy: 0.7727 - val_loss: 0.4888
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8165 - loss: 0.4055 - val_accuracy: 0.7727 - val_loss: 0.4891
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7975 - loss: 0.4136 - val_accuracy: 0.7727 - val_loss: 0.4893
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8120 - loss: 0.4103 - val_accuracy: 0.7597 - val_loss: 0.4908
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.3989 - val_accuracy: 0.7727 - val_loss: 0.4883
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8128 - loss: 0.4158 - val_accuracy: 0.7727 - val_loss: 0.4881
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4093 - val_accuracy: 0.7792 - val_loss: 0.4856
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8086 - loss: 0.4225 - val_accuracy: 0.7792 - val_loss: 0.4834
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8130 - loss: 0.3804 - val_accuracy: 0.7792 - val_loss: 0.4856
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7962 - loss: 0.4239 - val_accuracy: 0.7792 - val_loss: 0.4831
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8118 - loss: 0.3966 - val_accuracy: 0.7597 - val_loss: 0.4918
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8173 - loss: 0.4089 - val_accuracy: 0.7662 - val_loss: 0.4927
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8082 - loss: 0.4114 - val_accuracy: 0.7727 - val_loss: 0.4906
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8054 - loss: 0.4179 - val_accuracy: 0.7662 - val_loss: 0.4901
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8153 - loss: 0.4107 - val_accuracy: 0.7727 - val_loss: 0.4894
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8347 - loss: 0.3671 - val_accuracy: 0.7597 - val_loss: 0.4967
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8204 - loss: 0.3918 - val_accuracy: 0.7597 - val_loss: 0.4941
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3891 - val_accuracy: 0.7792 - val_loss: 0.4880
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3735 - val_accuracy: 0.7597 - val_loss: 0.4952
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8268 - loss: 0.4187 - val_accuracy: 0.7597 - val_loss: 0.4916
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8067 - loss: 0.4081 - val_accuracy: 0.7662 - val_loss: 0.4924
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8234 - loss: 0.3812 - val_accuracy: 0.7662 - val_loss: 0.4920
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3587 - val_accuracy: 0.7792 - val_loss: 0.4902
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8246 - loss: 0.3818 - val_accuracy: 0.7727 - val_loss: 0.4927
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8178 - loss: 0.4052 - val_accuracy: 0.7662 - val_loss: 0.4966
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8079 - loss: 0.4167 - val_accuracy: 0.7597 - val_loss: 0.4946
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8308 - loss: 0.3798 - val_accuracy: 0.7662 - val_loss: 0.4986
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3980 - val_accuracy: 0.7662 - val_loss: 0.4957
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8450 - loss: 0.3698 - val_accuracy: 0.7727 - val_loss: 0.4951
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8100 - loss: 0.3999 - val_accuracy: 0.7662 - val_loss: 0.4976
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8476 - loss: 0.3593 - val_accuracy: 0.7662 - val_loss: 0.5004
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8187 - loss: 0.4039 - val_accuracy: 0.7662 - val_loss: 0.4995
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8278 - loss: 0.3810 - val_accuracy: 0.7727 - val_loss: 0.4966
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8206 - loss: 0.4112 - val_accuracy: 0.7597 - val_loss: 0.4970
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8241 - loss: 0.3650 - val_accuracy: 0.7727 - val_loss: 0.4927
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8315 - loss: 0.3836 - val_accuracy: 0.7597 - val_loss: 0.4978
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8498 - loss: 0.3684 - val_accuracy: 0.7792 - val_loss: 0.4927
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8264 - loss: 0.3959 - val_accuracy: 0.7662 - val_loss: 0.4974
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8335 - loss: 0.3838 - val_accuracy: 0.7662 - val_loss: 0.4998
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8387 - loss: 0.3895 - val_accuracy: 0.7597 - val_loss: 0.4978
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8285 - loss: 0.4016 - val_accuracy: 0.7662 - val_loss: 0.4970
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8499 - loss: 0.3506 - val_accuracy: 0.7662 - val_loss: 0.5009
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8538 - loss: 0.3687 - val_accuracy: 0.7662 - val_loss: 0.4973
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8312 - loss: 0.3733 - val_accuracy: 0.7792 - val_loss: 0.5019
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8443 - loss: 0.3565 - val_accuracy: 0.7727 - val_loss: 0.4981
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8352 - loss: 0.3761 - val_accuracy: 0.7597 - val_loss: 0.5008
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8435 - loss: 0.3780 - val_accuracy: 0.7532 - val_loss: 0.5018
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8272 - loss: 0.3896 - val_accuracy: 0.7532 - val_loss: 0.5057
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8342 - loss: 0.3634 - val_accuracy: 0.7792 - val_loss: 0.5014